version: "3.9"

networks:
  int_network:

services:
  controlsvc:
    image: majumi/clientapp:application
    ports:
      - published: 5100
        target: 5100
    networks:
      - int_network
    deploy:
      replicas: 1
