version: "0.2"

networks:
  int_network:

services:
  carsdataservice:
    image: majumi/carsdataservice:dataservice
    ports:
      - published: 5000
        target: 5000
    networks:
      - int_network
  clientsdataservice:
    image: majumi/clientsdataservice:dataservice
    ports:
      - published: 5001
        target: 5001
    networks:
      - int_network
  visitsdataservice:
    image: majumi/visitsdataservice:dataservice
    ports:
      - published: 5003
        target: 5003
    networks:
      - int_network
  clientappservice:
    image: majumi/clientappservice:appservice
    ports:
      - published: 5010
        target: 5010
    networks:
      - int_network
  clientapp:
    image: majumi/clientapp:application
    ports:
      - published: 5100
        target: 5100
    networks:
      - int_network