apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapplication
  labels:
    app: webapplication
    tier: user-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapplication
  template:
    metadata:
      labels:
        app: webapplication
        tier: user-application
    spec:
      containers:
      - name: webapplication
        image: majumi/clientapp:application
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-secret
---
apiVersion: v1
kind: Service
metadata:
  name: webapplication
  labels:
    app: webapplication
    tier: user-application
spec:
  selector:
    app: webapplication
  type: NodePort
  ports:
  - port: 80
    nodePort: 30080
